version: "3"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - ${HTTP_PORT}:8080
    environment:
      - "DOZZLE_NO_ANALYTICS=true"
      - "DOZZLE_AUTH_PROVIDER=simple"
    restart: unless-stopped
